name: Test Claude OIDC

on:
  workflow_dispatch:

jobs:
  test-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Claude Code with stored credentials
        run: |
          mkdir -p ~/.claude
          echo '{
            "claudeAiOauth":{
              "accessToken": "${{ secrets.CLAUDE_ACCESS_TOKEN }}",
              "refreshToken": "${{ secrets.CLAUDE_REFRESH_TOKEN }}",
              "expiresAt": ${{ secrets.CLAUDE_EXPIRES_AT }},
              "scopes": [
                "user:inference",
                "user:profile"
              ]
            }
          }' > ~/.claude/.credentials.json
      
      - name: Ensure Claude is onboarded for interactive mode
        run: |
          echo '{
              "numStartups": 173,
              "autoUpdaterStatus": "migrated",
              "tipsHistory": {
                "new-user-warmup": 1,
                "terminal-setup": 80,
                "memory-command": 73,
                "theme-command": 135,
                "prompt-queue": 69,
                "todo-list": 140,
                "enter-to-steer-in-relatime": 154,
                "git-worktrees": 167,
                "claude-opus-welcome": 78,
                "shift-enter": 168,
                "ide-hotkey": 171
              },
              "memoryUsageCount": 6,
              "promptQueueUseCount": 15,
              "userID": "5d39a987b9ea56548f67f7b99ea032394b10ad05dd6380b86586c4f09415a39f",
              "hasCompletedOnboarding": true,
              "lastOnboardingVersion": "1.0.3",
              "projects": {},
          }' > ~/.claude.json

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
        
      - name: Test authentication
        run: claude --version
        
      - name: Start Claude in interactive mode to refresh token
        run: |
          # Use script command to create a pseudo-TTY and kill after 5 seconds
          timeout 5s script -q -c "claude" /dev/null || true
          
      - name: Test Claude with a prompt
        run: claude -p "Say Hello"