name: Test Claude OIDC

on:
  workflow_dispatch:

jobs:
  test-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Claude Code with stored credentials
        run: |
          mkdir -p ~/.claude
          echo '{
            "claudeAiOauth":{
              "accessToken": "${{ secrets.CLAUDE_ACCESS_TOKEN }}",
              "refreshToken": "${{ secrets.CLAUDE_REFRESH_TOKEN }}",
              "expiresAt": ${{ secrets.CLAUDE_EXPIRES_AT }},
              "scopes": [
                "user:inference",
                "user:profile"
              ]
            }
          }' > ~/.claude/.credentials.json
      
      - name: Ensure Claude is onboarded for interactive mode
        run: |
          echo '{
            "hasCompletedOnboarding": true,
            "lastOnboardingVersion": "1.0.3",
          }' > ~/.claude.json

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
        
      - name: Test authentication
        run: claude --version
        
      - name: Start Claude in interactive mode to refresh token
        run: |
          # Use script command to create a pseudo-TTY and kill after 5 seconds
          timeout 5s script -q -c "claude" /dev/null || true
          
      - name: Test Claude with a prompt
        run: claude -p "Say Hello"