name: Test Claude OIDC

on:
  workflow_dispatch:

jobs:
  test-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Claude Code with stored credentials
        run: |
          mkdir -p ~/.claude
          echo '{
            "claudeAiOauth":{
              "accessToken": "${{ secrets.CLAUDE_ACCESS_TOKEN}}",
              "refresh_token": "${{ secrets.CLAUDE_REFRESH_TOKEN }}",
              "expiresAt":1748195110003,
              "scope"[["user:inference","user:profile"]
            }
          }' > ~/.claude/credentials.json
          
      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code
        
      - name: Test authentication
        run: claude --version
        
      - name: Test Claude with a prompt
        run: claude -p "Say Hello"